### ISSUE TITLE
[FEAT] Version 4.6.0 released

### ISSUE THREAD

**Issue by mariushosting** [linuxserver/docker-darktable#10]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Linuxserver image support the old version 4.0.1 of Darktable

### Reason for change

Version 4.6.0 https://github.com/darktable-org/darktable/releases/tag/release-4.6.0

**Comment by thelamer** [comment]
Linking https://github.com/linuxserver/docker-darktable/pull/12

**Comment by thelamer** [comment]
Building now
