### ISSUE TITLE
Could you please ad git to the image?

### ISSUE THREAD

**Issue by ovizii** [linuxserver/docker-darktable#3]
## Desired Behavior
darktable offers to install the lua scripts repository. Doing so would be great.

## Current Behavior
darktable needs git to do so

![image](https://user-images.githubusercontent.com/837902/121646896-1455bb00-ca96-11eb-88cc-71e55efacb21.png)

**Comment by tobbenb** [comment]
You can use the docker mod to install git. See the readme for info.

**Comment by ovizii** [comment]
Thanks, I checked the readme, followed the link to mods and please correct me if I am wrong but do I need to create a repository, create a mod and upload it and then link the mod to your darktable image when running?

Any more links for me to figure this out?

**Comment by ovizii** [comment]
damn, I think I figured it out: I was specifically looking for darktable mods until I found the universal ones. I guess this is what you were referring to?

https://github.com/linuxserver/docker-mods/tree/universal-git

**Comment by tobbenb** [comment]
Yes, universal is for all images 😉
